# Generated by Django 3.2.5 on 2022-07-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0005_auto_20220730_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputmodel',
            name='subjects',
            field=models.CharField(choices=[(1, 'Math'), (2, 'Physics'), (3, 'Chemistry'), (4, 'Informatics'), (5, 'Speech')], default='Math', max_length=200),
        ),
    ]
