name: API CI

on:
  push:
    paths:
      - "api/**"
      - ".github/workflows/api-ci.yml"

defaults:
  run:
    working-directory: ./api

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'
          cache-dependency-path: ./api/package-lock.json
      - name: install
        shell: bash
        run: npm ci
      - name: run linter
        shell: bash
        run: npm run lint
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "npm"
          cache-dependency-path: ./api/package-lock.json

      - name: Install dependencies
        shell: bash
        run: npm ci

      - name: Run unit tests
        shell: bash
        run: npm test
  e2e:
    runs-on: ubuntu-latest
    container:
      image: node:14

    services:
      mongo-e2e:
        image: mongo:4.4
        ports:
          - 27020:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: test
          MONGO_INITDB_ROOT_PASSWORD: test123

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        shell: bash
        run: npm ci

      - name: Run e2e tests
        shell: bash
        run: npm run test:e2e
        env:
          MONGO_URL: mongodb://test:test123@mongo-e2e:27020?retryWrites=true&writeConcern=majority
          MONGO_DB_NAME: demo