# Generated by Django 3.2.5 on 2022-07-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('roll_number', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='geeksmodel',
            name='description',
            field=models.TextField(help_text='Enter the description of the post'),
        ),
        migrations.AlterField(
            model_name='geeksmodel',
            name='img',
            field=models.ImageField(help_text='Upload the image of the post', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='geeksmodel',
            name='title',
            field=models.CharField(help_text='Enter the title of the post', max_length=200),
        ),
    ]
