# Generated by Django 3.2.5 on 2022-07-30 05:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0003_auto_20220730_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputmodel',
            name='subjects',
        ),
        migrations.AlterField(
            model_name='inputmodel',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 30, 5, 45, 30, 507257, tzinfo=utc)),
        ),
    ]
