# Generated by Django 3.2.5 on 2022-07-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0004_auto_20220730_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputmodel',
            name='subjects',
            field=models.CharField(default='Math', max_length=200),
        ),
        migrations.AlterField(
            model_name='inputmodel',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
