# Generated by Django 3.2.5 on 2022-07-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0006_alter_inputmodel_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputmodel',
            name='subjects',
            field=models.CharField(choices=[('Math', 'Math'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Informatics', 'Informatics'), ('Speech', 'Speech')], default='Math', max_length=200),
        ),
    ]
